Repository pyupio/pyup, pull requests merged in 2020-12, with the labels that each got.

#193 Cache api instance
  pyup/providers/github.py
  tests/test_github.py
Labels: enhancement

#385 GitLab: merge with correct arguments
  HISTORY.rst
  pyup/providers/gitlab.py
  tests/test_gitlab.py
Labels: bug

#387 Refactoring of the method Update.create_update_key
  pyup/updates.py
Labels: refactoring

#389 Commit messages can now be configured via config.
  AUTHORS.rst
  HISTORY.rst
  pyup/config.py
  pyup/updates.py
  tests/test_config.py
  tests/test_updates.py
Labels: enhancement
