Repository pyupio/pyup, pull requests merged in 2020-03, with the labels that each got.

#367 Rework how we do compatible releases
  pyup/requirements.py
  tests/test_requirements.py
Labels: enhancement

#362 Add option to ignore SSL certificate
  README.rst
  pyup/bot.py
  pyup/cli.py
  pyup/providers/github.py
  pyup/providers/gitlab.py
  tests/test_bot.py
  tests/test_github.py
  tests/test_gitlab.py
Labels: new feature

#375 remove leading slash from .pyup.yml to fix bug on gitlab api
  pyup/bot.py
  pyup/providers/gitlab.py
Labels: bug
